/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paseo;

/**
 *
 * @author pedro
 */
public class Paseo extends javax.swing.JFrame {

    /**
     * Creates new form Paseo
     */
    public Paseo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        RDBTN_BOSQUE = new javax.swing.JRadioButton();
        RDBTN_CC = new javax.swing.JRadioButton();
        btn_paseo = new javax.swing.JButton();
        lbl_paseo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbl_comida = new javax.swing.JLabel();
        chk_1 = new javax.swing.JCheckBox();
        chk_3 = new javax.swing.JCheckBox();
        chk_2 = new javax.swing.JCheckBox();
        chk_4 = new javax.swing.JCheckBox();
        btn_comida = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_comida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("donde quieres ir?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton1.setText("playa");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(RDBTN_BOSQUE);
        RDBTN_BOSQUE.setForeground(new java.awt.Color(0, 0, 0));
        RDBTN_BOSQUE.setText("bosque");
        RDBTN_BOSQUE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDBTN_BOSQUEActionPerformed(evt);
            }
        });

        buttonGroup1.add(RDBTN_CC);
        RDBTN_CC.setForeground(new java.awt.Color(0, 0, 0));
        RDBTN_CC.setText("centro comercial");
        RDBTN_CC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDBTN_CCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RDBTN_BOSQUE, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RDBTN_CC))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jRadioButton1)
                .addGap(51, 51, 51)
                .addComponent(RDBTN_BOSQUE)
                .addGap(51, 51, 51)
                .addComponent(RDBTN_CC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_paseo.setText("Donde ir");
        btn_paseo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_paseoActionPerformed(evt);
            }
        });

        lbl_paseo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_paseo.setForeground(new java.awt.Color(0, 0, 255));
        lbl_paseo.setText("Nada");

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        lbl_comida.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_comida.setForeground(new java.awt.Color(0, 0, 0));
        lbl_comida.setText("que te gusta?");

        chk_1.setText("pizza");

        chk_3.setText("pasta");

        chk_2.setText("carne");

        chk_4.setText("pupusas");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(chk_1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_comida, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chk_4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_comida)
                .addGap(29, 29, 29)
                .addComponent(chk_1)
                .addGap(33, 33, 33)
                .addComponent(chk_2)
                .addGap(30, 30, 30)
                .addComponent(chk_3)
                .addGap(30, 30, 30)
                .addComponent(chk_4)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        btn_comida.setText("te gusta:");
        btn_comida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comidaActionPerformed(evt);
            }
        });

        txta_comida.setColumns(20);
        txta_comida.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txta_comida.setRows(5);
        jScrollPane1.setViewportView(txta_comida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_paseo, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_paseo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_comida)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_paseo)
                    .addComponent(btn_comida))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_paseo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void RDBTN_BOSQUEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDBTN_BOSQUEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDBTN_BOSQUEActionPerformed

    private void RDBTN_CCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDBTN_CCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RDBTN_CCActionPerformed

    private void btn_paseoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_paseoActionPerformed
        if (jRadioButton1.isSelected()) {
            lbl_paseo.setText("playa");
        }else
            
        if (RDBTN_BOSQUE.isSelected()) {
            lbl_paseo.setText("BOSQUE");
        }else
            if (RDBTN_CC.isSelected()) {
            lbl_paseo.setText("playa");
        }
    }//GEN-LAST:event_btn_paseoActionPerformed

    private void btn_comidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comidaActionPerformed
        String teGusta="";
        
        if (chk_1.isSelected()) {
            teGusta += " pizza ";
        }
        if (chk_2.isSelected()) {
            teGusta += "carne ";
        }
        if (chk_3.isSelected()) {
            teGusta += "pasta ";
        }
        if (chk_4.isSelected()) {
            teGusta += "pupusas ";
        }
        
        txta_comida.setText(teGusta);
    }//GEN-LAST:event_btn_comidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paseo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Paseo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RDBTN_BOSQUE;
    private javax.swing.JRadioButton RDBTN_CC;
    private javax.swing.JButton btn_comida;
    private javax.swing.JButton btn_paseo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chk_1;
    private javax.swing.JCheckBox chk_2;
    private javax.swing.JCheckBox chk_3;
    private javax.swing.JCheckBox chk_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_comida;
    private javax.swing.JLabel lbl_paseo;
    private javax.swing.JTextArea txta_comida;
    // End of variables declaration//GEN-END:variables
}
